apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.codewind.eclipse.org
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.namespace
    description: Deployment namespace
    name: Namespace
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: Age of the resource
    name: Age
    type: date
  - JSONPath: .status.url
    description: Exposed route
    name: Access
    type: string
  group: codewind.eclipse.org
  names:
    kind: Keycloak
    listKind: KeycloakList
    plural: keycloaks
    singular: keycloak
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Keycloak is the Schema for the keycloaks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          ###type: object
        spec:
          description: KeycloakSpec defines the desired state of Keycloak
          properties:
            storageSize:
              description: 'Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file StorageSize : Size of the Keycloak
                PVC'
              pattern: '[0-9]*Gi$'
              type: string
          required:
          - storageSize
          ###type: object
        status:
          description: KeycloakStatus defines the observed state of Keycloak
          properties:
            defaultRealm:
              type: string
            phase:
              description: 'Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file'
              type: string
            url:
              type: string
          required:
          - defaultRealm
          - phase
          - url
          ###type: object
      ###type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
