# /*******************************************************************************
#  * Copyright (c) 2020 IBM Corporation and others.
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the Eclipse Public License v2.0
#  * which accompanies this distribution, and is available at
#  * http://www.eclipse.org/legal/epl-v20.html
#  *
#  * Contributors:
#  *     IBM Corporation - initial API and implementation
#  *******************************************************************************/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: codewind-operator
  namespace: codewind
spec:
  replicas: 1
  selector:
    matchLabels:
      name: codewind-operator
  template:
    metadata:
      labels:
        name: codewind-operator
    spec:
      serviceAccountName: codewind-operator
      containers:
        - name: codewind-operator
          image: eclipse/codewind-operator-amd64:0.13.0
          command:
          - codewind-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "codewind-operator"
