# /*******************************************************************************
#  * Copyright (c) 2020 IBM Corporation and others.
#  * All rights reserved. This program and the accompanying materials
#  * are made available under the terms of the Eclipse Public License v2.0
#  * which accompanies this distribution, and is available at
#  * http://www.eclipse.org/legal/epl-v20.html
#  *
#  * Contributors:
#  *     IBM Corporation - initial API and implementation
#  *******************************************************************************/

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codewind-operator
  namespace: codewind
subjects:
- kind: ServiceAccount
  name: codewind-operator
roleRef:
  kind: Role
  name: codewind-operator
  apiGroup: rbac.authorization.k8s.io
